apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1 # Start with 1 replica
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: bilelbouzid/todoapp:latest # Replace with your Docker Hub image
          ports:
            - containerPort: 5002
          resources: # Add resource requests and limits (important for production)
            requests:
              cpu: 100m
              memory: 200Mi
            limits:
              cpu: 200m
              memory: 400Mi