name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Build frontend
        working-directory: ./frontend
        run: |
          npm install
          npm run build

      - name: Build backend Docker image
        working-directory: ./backend
        run: |
          docker build -t bilelbouzid/todoapp:latest .
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker push bilelbouzid/todoapp:latest

      - name: Build frontend Docker image
        working-directory: ./frontend
        run: |
          docker build -t bilelbouzid/todoappfrontend:latest .
          docker push bilelbouzid/todoappfrontend:latest

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.26.0' # Or your Kubernetes version

      - name: Configure kubectl
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" | base64 -d > ~/.kube/config
          kubectl config current-context # Verify the context (important for debugging)

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/backend-deployment.yaml
          kubectl apply -f k8s/backend-service.yaml
          kubectl apply -f k8s/frontend-deployment.yaml
          kubectl apply -f k8s/frontend-service.yaml